FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY ./ProcessTelemetry/*.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish "ProcessTelemetry/ProcessTelemetry.csproj" -c Release -o out

FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/ProcessTelemetry/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "ProcessTelemetry.dll"]