FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY ./DoserTelemetry/*.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish "DoserTelemetry/DoserTelemetry.csproj" -c Release -o out

FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/DoserTelemetry/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "DoserTelemetry.dll"]